version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: docker/php7-fpm
        volumes:
            - .:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/app/logs:cached
    nginx:
        build: docker/nginx
        ports:
            - 8080:8080
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
            - .:/var/www/symfony:cached
    redis:
        image: redis