app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /app/{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
homepage:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/index.html.twig
        _locale:     '%locale%'
certification:
    resource: '@CertificationBundle/Controller/'
    type: annotation
    prefix: /certification/